name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - master # Ganti dengan branch yang ingin Anda deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AUTHORIZED_KEY }}" > ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        chmod 700 ~/.ssh

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 root@192.168.26.42 "cd /home/project-python && git pull"
